# Generated by Django 4.2.8 on 2024-01-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bard', '0033_remove_userprofile_full_name_alter_userprofile_user'),
        ('bard', '0043_alter_confirmationcode_code_delete_customuser'),
    ]

    operations = [
    ]
